import { pgTable, text, timestamp, boolean, integer } from "drizzle-orm/pg-core";
import { user } from "./user.schema";

// ============================================
// BETTER AUTH API KEY PLUGIN
// This table is managed by Better Auth's API Key plugin
// ============================================

export const apiKey = pgTable("api_key", {
  // Core Identity Fields
  id: text("id").primaryKey(),
  name: text("name").notNull(),

  // Key Management
  start: text("start"), // First few chars for UI display (auto-generated by Better Auth)
  prefix: text("prefix"), // Custom prefix (e.g., 'zuno_')
  key: text("key").notNull().unique(), // Hashed API key - Better Auth handles hashing

  // User Association
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),

  // Rate Limiting (Built-in Better Auth feature)
  rateLimitEnabled: boolean("rate_limit_enabled").default(false),
  rateLimitTimeWindow: integer("rate_limit_time_window"), // Time window in ms
  rateLimitMax: integer("rate_limit_max"), // Max requests per window
  requestCount: integer("request_count").default(0), // Current request count

  // Usage Tracking & Refill System
  remaining: integer("remaining"), // Remaining requests (for quota system)
  refillAmount: integer("refill_amount"), // Amount to refill when refilling
  refillInterval: integer("refill_interval"), // Interval in ms to refill
  lastRefillAt: timestamp("last_refill_at"), // When was last refill
  lastRequest: timestamp("last_request"), // When was last API request

  // Status & Expiration
  enabled: boolean("enabled").default(true).notNull(), // Is key active/enabled
  expiresAt: timestamp("expires_at"), // Optional expiration date

  // Permissions System (Better Auth built-in)
  permissions: text("permissions"), // JSON string: '{"metadata":["read","write"],"media":["read"]}'

  // Custom Metadata (Your business logic)
  // Note: Better Auth expects this to be text, not jsonb
  metadata: text("metadata").$type<{
    // Key type
    type?: "personal" | "organization" | "public";
    // Custom scopes (application-specific)
    scopes?: string[]; // ['read:metadata', 'write:metadata', 'read:media']

    // Security restrictions
    ipWhitelist?: string[]; // ['192.168.1.1', '10.0.0.0/8']
    allowedOrigins?: string[]; // ['https://example.com']

    notes?: string; // Internal notes about this key
  }>(),

  // Timestamps
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
}).enableRLS();

// Export types for TypeScript inference
export type ApiKey = typeof apiKey.$inferSelect;
export type NewApiKey = typeof apiKey.$inferInsert;
